{{ if eq .Values.ingress true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  namespace: voting-app
spec:
  rules:
    - host: {{ .Values.vote_address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vote-ui
                port:
                  number: 80
    - host: {{ .Values.results_address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: result-ui
                port:
                  number: 80
{{ end }}
