# Image registry with repository
registry: cr.alusta.cloud/demo

# Version of the VotingApp among v1, v2 and v3
version: v2

# Show images instead of labels
images:
  vote: false
  result: false

# Version of the worker among java, dotnet and go
worker:
  language: go

# Ingress and external hostname (FQDN) to use
ingress: false
vote_address: vote.example.com
results_address: results.example.com